// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nezvfjxihrwuhkbufxkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lenZmanhpaHJ3dWhrYnVmeGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTk1MDQsImV4cCI6MjA2NTUzNTUwNH0.QGohohNNt5WTr2zcy134JXrck3c89nIuGoik2GRlm_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);